#versao do compose
version: '3'

services:
  db:
    image: mysql:5.7
    #mysql precisa desse comando
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      #tudo gravado na var/lib/mysql fica saldo no volume externo
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
networks:
  node-network:
    driver: bridge
