#versao do compose
version: '3'

services:
  db:
    image: mysql:5.7
    #mysql precisa desse comando
    command: --innodb-use-native-aio=0
    container_name: db
    #restart: always
    tty: true
    volumes:
      #tudo gravado na var/lib/mysql fica saldo no volume externo
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    #espera o db buildar antes de buildar o node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"


networks:
  node-network:
    driver: bridge
